---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux-memcached
  template:
    metadata:
      labels:
        app: flux-memcached
    spec:
      containers:
      - name: memcached
        image: memcached:1.4.25
        imagePullPolicy: IfNotPresent
        args:
        - -m 64    # Maximum memory to use, in megabytes. 64MB is default.
        - -p 11211    # Default port, but being explicit is nice.
        - -I 1m #  Maximum size for one item
        ports:
        - name: memcached
          containerPort: 11211
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 64Mi

---
apiVersion: v1
kind: Service
metadata:
  name: flux-memcached
spec:
  ports:
    - name: memcached
      port: 11211
  selector:
    app: flux-memcached
